### ISSUE TITLE
Setup PWA

### ISSUE THREAD

**Issue by RusinovAnton** [tl-dr-community/js-tldr#106]
- [x] - turn on the serviceWorker
- [x] - update manifest.json
- [ ] - setup http -> https redirect

**Comment by nnmrts** [comment]
Lol, just had this idea too and almost opened a new issue. Can I help you with that?

**Comment by RusinovAnton** [comment]
yup! go ahead. let me know if you need something

**Comment by nnmrts** [comment]
@RusinovAnton That was easier than I thought. 😅 

Pull request:
https://github.com/RusinovAnton/js-tldr/pull/114

**Comment by RusinovAnton** [comment]
Thanks for the PR! 

I think before merging it, on top of these improvements we need to update manifest.json to have right colors, logos images etc

Another thing I've just noticed reading the  serviceWorker.js code:

```
// Our service worker won't work if PUBLIC_URL is on a different origin
// from what our page is served on. This might happen if a CDN is used to
// serve assets; see https://github.com/facebook/create-react-app/issues/2374
```

so we need to set the PUBLIC_URL at .env


Regarding the http->https redirect, the ticket for gcloud is still opened, they promised to deliver this feature q4 2019 tho

https://googlecloudplatform.uservoice.com/forums/302616-load-balancing/suggestions/31951531-allow-http-to-redirect-to-https-automatically

**Comment by nnmrts** [comment]
Thanks for approving it. Alright, I'll look into this.

Regarding the http to https:
I managed a few gcloud projects in the past but not recently, so I don't know about the "freedom" there anymore, but can't you just add a .htaccess file to your root directory? Or add some middleware to your node.js server?

But I'm guessing you're just serving a static site (just the "build" folder) here, right? Maybe this needs more changes than I initially thought. It's not a lot of work, but still a major design choice to switch from a static site to something like an expressjs server, so I would actually suggest to leave the PWA stuff, as much as I would love it to see it implemented, out of the 1.0.0 release and leave it for later.

Thoughts on this? Or maybe insights about your gcloud setup?

**Comment by RusinovAnton** [comment]
Regarding manifest and logos I've already added them. 

It's my first time using gcloud so I don't really know what should I look for, it's just some info I've googled after your suggestion on the redirect. I couldn't find any sensible solution for nodejs as well, just some dumb midldeware that I don't really want to use. So if you'd tell me where to start looking for that setup, I would provide you on whether I can/can't do that in my gcloud acc. Thanks

**Comment by nnmrts** [comment]
Well, most important question, are you actually using gcloud's App Engine? Or Firebase?

**Comment by RusinovAnton** [comment]
It's definitely App Engine

**Comment by nnmrts** [comment]
Have you tried adding this to your app.yaml file?

```
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
```

([source](https://cloud.google.com/appengine/docs/standard/nodejs/application-security))

**Comment by RusinovAnton** [comment]
Thanks! I've deployed the config with the parameters but it doesn't redirect me to https if I go to http address 

https://github.com/RusinovAnton/js-tldr/commit/2b9da988ad30ce2244d9ebe4ea116e416822e86a/checks?check_suite_id=336621546

![image](https://user-images.githubusercontent.com/13165540/69918311-168a9280-1479-11ea-9a74-b6d3a2703548.png)

**Comment by nnmrts** [comment]
Ahhh, I know this problem. Https redirect doesn't work for flex environments. Handlers in general are ignored when you use flex. Are you able to switch from flex to standard?

If you do this, make sure you close all other instances of the app.
<hr>
Oh and btw, if you go directly to the https version of js-tldr, PWA WORKS! 🎉 
<img width="544" alt="Bildschirmfoto 2019-12-02 um 06 21 49" src="https://user-images.githubusercontent.com/20396367/69932626-15cf1c00-14cc-11ea-9644-7cb40c8daec7.png">
<img width="1124" alt="Bildschirmfoto 2019-12-02 um 06 22 54" src="https://user-images.githubusercontent.com/20396367/69932661-41520680-14cc-11ea-94c6-252577a49f6f.png">

This is awesome.

**Comment by nnmrts** [comment]
My long term suggestion would still be to use expressjs with yes-https in the background, so you don't have to mess around with the app.yaml

**Comment by RusinovAnton** [comment]
I would go with the expressjs approach instead moving from flex to standard. Right now, "serve" library is simply used to run the app on production and should be replaced.

**Comment by nnmrts** [comment]
Alright, sounds good. Do you want to open a new issue for migrating to expressjs? I can work on that in the next few days. :)

**Comment by RusinovAnton** [comment]
It can be done in scope of this one, I think. Thank you!

**Comment by RusinovAnton** [comment]
http -> https now provided by hosting - Netlify

**Comment by nnmrts** [comment]
Nice to hear! Sorry I couldn't continue to work on this, I was busy with a lot of other stuff the last few months.

**Comment by RusinovAnton** [comment]
No worries! Thanks for your contributions :)
