### ISSUE TITLE
fix input autofocus

### ISSUE THREAD

**Issue by RusinovAnton** [tl-dr-community/js-tldr#112]
there is autofocus prop set to input, but it doesn't work

Actual result: 

Search input does not have a focus on the homepage load

Expected result:

search input get focused when user comes to the homepage

**Comment by gemanepa** [comment]
@RusinovAnton can you elaborate when the autofocus is not happening when it should? It seems to be working after one of the 5 doc buttons have been pressed but not before, and it's not clear what's the expected behavior you want

**Comment by RusinovAnton** [comment]
@gemanepa 

you may see that there is the `autoFocus` prop set to the input:
https://github.com/RusinovAnton/js-tldr/blob/master/src/scenes/Search/SearchInput.js#L15

I expect it to have focus when I go to the '/', by loading website initially or/and by coming to the homepage '/' from any other page. Right now it doesn't work, looks like some re-render magic or ~something is being focused but is not visible.~

You can see that the `body` element is active on initial page load

![image](https://user-images.githubusercontent.com/13165540/70172789-1ccb7980-16da-11ea-9189-fb92f359631d.png)
