### ISSUE TITLE
Add cursor and hover states to clickable elements

### ISSUE THREAD

**Issue by Gilstroem** [tl-dr-community/js-tldr#116]
Great project 👍🏼🙏🏼

I noticed that almost no elements (apart from links) have any of the features you'd expect from clickable items; at the very least, a cursor: pointer would be good, some other hover state (e.g. box-shadow or darkening text) might be good as well.

The elements lacking are the yes/no helpful buttons, the 'domains' (Number etc.) selection buttons, and the X button when a doc is selected

**Comment by RusinovAnton** [comment]
Thank you for your feedback. Right now it's no priority for me but I'll gladly consider a PR.

Btw, its a standard that `cursor: pointer` appears for links only

**Comment by gemanepa** [comment]
I agree with @Gilstroem that UX-wise, it feels particularly weird and counterintuitive to not see any indication that the 5 docs buttons in the main page are clickeable elements

**Comment by RusinovAnton** [comment]
been fixed
