### ISSUE TITLE
Error occur Clicking the button as soon as Main rendered 

### ISSUE THREAD

**Issue by insulatir** [tl-dr-community/js-tldr#134]
As soon as rendered Main page, Typing in the box or Click the button has occur 'Uncaught TypeError: Cannot read property 'search' of null'. 

I think this is because data from server has not arrived but Main page already rendered. 

Can I work this?

**Comment by RusinovAnton** [comment]
Thanks for reporting this! Sure, PRs are welcome

**Comment by TonnTamerlan** [comment]
@RusinovAnton can I work with it?

**Comment by RusinovAnton** [comment]
@TonnTamerlan yup! <3

**Comment by TonnTamerlan** [comment]
@RusinovAnton not reproducible neither local nor prod

**Comment by RusinovAnton** [comment]
Thanks for checking, same for me. I'll close this ticket then. Feel free to choose another one
