### ISSUE TITLE
UI Bug: results dropdown doesn't cover chips buttons

### ISSUE THREAD

**Issue by RusinovAnton** [tl-dr-community/js-tldr#154]
AS IS:
When the results dropdown is opened, there is a cut "Array" chip button is visible, which is not looking aesthetic
![image](https://user-images.githubusercontent.com/13165540/88076837-3c3ce700-cb83-11ea-99bf-1cbbf6a52331.png)

TO BE:
No buttons should be visible. 

I think of two things: 
- either hide buttons if results are visible or even input has some value
- make dropdown wider to cover everything underneath the input

other suggestions are welcome

**Comment by vkabish** [comment]
✋

**Comment by RusinovAnton** [comment]
Been successfully deployed. Thank you for your help!
